
- platform: mqtt
  name: "Coffee"
  state_topic: "stat/coffee/POWER"
  command_topic: "cmnd/coffee/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: false
- platform: mqtt
  name: "Ender"
  state_topic: "stat/3dprinter/POWER1"
  command_topic: "cmnd/3dprinter/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
- platform: mqtt
  name: "OctoPrint"
  state_topic: "stat/3dprinter/POWER2"
  command_topic: "cmnd/3dprinter/POWER2"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true