- id: is_anybody_home
  alias: Set a tag, anybody entering home zone
  trigger:
  - platform: state
    to: home
    entity_id: person.izer_nandor_jr
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.somebody_at_home
- id: scene_anybody_home
  alias: Scene set when anybody arrives home
  trigger:
  - platform: state
    entity_id: binary_sensor.frontdoor
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.cover_open_if_sun_above_horizon
    data: {}
  - service: script.minimal_light_if_sun_below_horizon
    data: {}
  - service: light.turn_on
    target:
      entity_id: light.tablet_screens
    data: {}
  - service: automation.turn_off
    entity_id: automation.scene_set_when_anybody_arrives_home
  initial_state: false
- id: scene_everybody_away
  alias: Scene set when everybody leaves home
  trigger:
  - platform: state
    from: home
    entity_id: person.izer_nandor_jr
  condition:
  - condition: template
    value_template: "{% if is_state('person.izer_nandor_jr', 'home') %}\n  false\n\
      {% else %}\n  true\n{% endif %}\n"
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.somebody_at_home
  - service: automation.turn_on
    entity_id: automation.scene_set_when_anybody_arrives_home
  - service: scene.turn_on
    target:
      entity_id: scene.covers_night
  - service: light.turn_off
    data:
      entity_id: all
  - service: switch.turn_off
    entity_id: switch.coffee
  - service: media_player.turn_off
    target:
      entity_id: media_player.tv
- id: scene_by_rfkey1
  alias: Morning scene by remote key A
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey == 1 }}'
  action:
  - service: media_player.turn_on
    entity_id: media_player.hifi
  - service: script.cover_open_if_sun_above_horizon
  - service: script.minimal_light_if_sun_below_horizon
- id: scene_by_rfkey2
  alias: Close covers by remote key B
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey == 2 }}'
  action:
    service: scene.turn_on
    entity_id: scene.covers_night
- id: scene_by_rfkey3
  alias: Full open covers by remote key C
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey == 3 }}'
  action:
    service: scene.turn_on
    entity_id: scene.covers_day
- id: scene_by_rfkey4
  alias: Full close covers by remote key D
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey == 4 }}'
  action:
    service: scene.turn_on
    entity_id: scene.covers_night
- id: scene_by_rfkey5
  alias: Toggle bedroom light by A
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey == 5 }}'
  action:
    service: light.toggle
    entity_id: light.halo
- id: scene_by_rfkey6
  alias: Open bedroom cover by remote key B
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey == 6 }}'
  action:
    service: scene.turn_on
    entity_id: scene.cover_kisszoba_day
- id: scene_by_rfkey8
  alias: Close bedroom cover by remote key D
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey == 8 }}'
  action:
    service: scene.turn_on
    entity_id: scene.cover_kisszoba_night
- id: start_coffee_timer
  alias: Start Coffee timer
  trigger:
  - entity_id: switch.coffee
    platform: state
    to: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.coffee
  - service: timer.start
    entity_id: timer.coffee
    data_template:
      duration: "{{ ((states('input_number.coffee_on_time')|int) * 60)\n     |timestamp_custom('%X',false)\
        \ }}\n"
- id: coffee_off_by_timer
  alias: Switch off Coffee by timer
  trigger:
  - entity_id: switch.coffee
    platform: state
    to: 'off'
  - event_data:
      entity_id: timer.coffee
    event_type: timer.finished
    platform: event
  action:
  - service: switch.turn_off
    entity_id: switch.coffee
  - service: timer.cancel
    entity_id: timer.coffee
- id: entrance_light_on_by_movement
  alias: Entrance light by motion detector
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_entrance
    to: 'on'
  condition: []
  action:
  - service: timer.cancel
    entity_id: timer.light_entrance
  - service: timer.start
    entity_id: timer.light_entrance
    data_template:
      duration: "{{ states('input_number.light_entrance_time')|int\n     |timestamp_custom('%X',false)\
        \ }}\n"
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.illumination_entrance
      below: '10'
    - condition: state
      entity_id: light.szelfogo
      state: 'off'
  - service: light.turn_on
    entity_id: light.szelfogo
    data:
      brightness_pct: 10
- id: entrance_light_off_by_timer
  alias: Entrance light off timer
  trigger:
  - event_data:
      entity_id: timer.light_entrance
    event_type: timer.finished
    platform: event
  action:
  - condition: state
    entity_id: light.etkezo
    state: 'off'
  - service: light.turn_on
    entity_id: light.szelfogo
    data:
      brightness: 0
      transition: 3
- id: corridor_light_on_by_movement
  alias: Corridor light by motion detector
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_corridor
    to: 'on'
  condition: []
  action:
  - service: timer.cancel
    entity_id: timer.light_corridor
  - service: timer.start
    entity_id: timer.light_corridor
    data_template:
      duration: "{{ states('input_number.light_corridor_time')|int\n     |timestamp_custom('%X',false)\
        \ }}\n"
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.illumination_corridor
      below: 10
    - condition: state
      entity_id: light.kozlekedo
      state: 'off'
  - service: light.turn_on
    entity_id: light.kozlekedo
    data:
      brightness_pct: 10
- id: corridor_light_off_by_timer
  alias: Corridor light off timer
  trigger:
  - event_data:
      entity_id: timer.light_corridor
    event_type: timer.finished
    platform: event
  action:
  - condition: state
    entity_id: light.etkezo
    state: 'off'
  - service: light.turn_on
    entity_id: light.kozlekedo
    data:
      brightness: 0
      transition: 3
- id: reset_rf_sensors
  alias: Reset RF sensors state
  trigger:
    platform: mqtt
    topic: tele/rf-bridge/RESULT
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.RfReceived.RfKey > 0 }}'
  action:
  - delay:
      seconds: 3
  - service: mqtt.publish
    data:
      topic: tele/rf-bridge/RESULT
      payload: '{ "RfReceived" : { "RfKey" : 0 }}'
- id: bedlight_by_xiaomi_button
  alias: Bed light by Xiaomi button
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:02:0e:b3:9f
      command: click
      args:
        click_type: single
  action:
    service: light.toggle
    entity_id: light.livingroom_bedlight
- id: roomlight_by_xiaomi_button
  alias: Livingroom light by Xiaomi button
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:02:0e:b3:9f
      command: click
      args:
        click_type: double
  action:
    service: light.toggle
    entity_id: light.szoba
- id: blackout_by_xiaomi_button
  alias: Blackout lights by Xiaomi button
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:02:0e:b3:9f
      command: hold
  action:
  - service: light.turn_off
    entity_id: light.offgroup
  - service: light.turn_off
    target:
      entity_id: light.tablet_screens
  mode: single
- id: '1644167881016'
  alias: Turn On TV
  description: ''
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv_mac: 64:95:6C:1C:6F:B7
      webostv: media_player.tv
- id: '1644168250343'
  alias: Morning automation
  description: ''
  trigger:
  - platform: time
    at: sensor.oneplus_a5000_next_alarm
  condition:
  - condition: state
    entity_id: person.izer_nandor_jr
    state: home
  action:
  - service: script.turn_on
    data: {}
    target:
      entity_id: script.morning_routine
  mode: single
- id: '1649423891802'
  alias: Tablet on by motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_etkezo
    to: 'on'
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: button.falipanel_etkez_bring_to_foreground
  mode: single
