homeassistant:
  name: Juniors Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_elev
  unit_system: metric
  time_zone: Europe/Budapest
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  external_url: !secret my_url
  internal_url: !secret my_url
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.12.0/24
        - 127.0.0.1
    - type: homeassistant

#customizer:
#  custom_ui: local

mqtt:
  discovery: true
  discovery_prefix: homeassistant

#system_health:

lovelace:
#  mode: yaml

http: !include inc/http.yaml

frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

#config:

default_config:

zha_toolkit:

zha:
  zigpy_config:
    ezsp_config:
      CONFIG_MAX_END_DEVICE_CHILDREN: 0

#mobile_app:

wake_on_lan:

updater:
  include_used_components: true

discovery:
  # enable:
  #   - homekit

influxdb:
  host: localhost
  port: 8086
  ssl: false
  database: home_assistant
  username: hassio
  password: hassio

history:
  exclude:
    domains:
      - device_tracker

recorder:
  exclude:
    domains:
      - camera
      - media_player
      - automation
      - weblink
      - updater
      - cover
      - input_number
      - input_boolean
    entity_globs:
      - binary_sensor.*_charging
      - sensor.*_rx
      - sensor.*_tx
      - sensor.transmission_*
      - switch.transmission_*
      - sensor.*battery*
    entities:
      - binary_sensor.updater  
      - sensor.hacs

#logbook:

sun:
  name: Sun

zone: !include inc/zones.yaml
light: !include_dir_merge_list lights/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
cover: !include inc/covers.yaml
scene: !include scenes.yaml

nissan_leaf:
  username: !secret nissan_user
  password: !secret nissan_pass
  region: "NE"
  update_interval:
    hours: 3
  update_interval_charging:
    minutes: 30
  update_interval_climate:
    minutes: 15

notify:
  - platform: group
    name: "Notify group"
    services:
      - service: notify
      - service: tv

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

ffmpeg:

camera: !include inc/cameras.yaml

automation: !include automations.yaml

input_number: !include inc/inputs.yaml

input_boolean:
  toclean_common:
    name: Clean common places
    initial: off
  toclean_kitchen:
    name: Clean the kitchen
    initial: off
  toclean_bedroom:
    name: Clean the bedroom
    initial: off
  toclean_livingroom:
    name: Clean the livingroom
    initial: off
  somebody_at_home:
    name: Somebody entered Home zone
    initial: off

script: !include scripts.yaml
timer: !include inc/timers.yaml