#- platform: mqtt
#  name: "Ceiling"
#  state_topic: "stat/light_room/POWER"
#  command_topic: "cmnd/light_room/POWER"
#  qos: 1
#  payload_on: "ON"
#  payload_off: "OFF"
#  retain: true
- platform: mqtt
  name: "Bedroom"
  state_topic: "stat/bedroom-light/POWER1"
  command_topic: "cmnd/bedroom-light/POWER1"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true  
