# - platform: group
#   name: Eloterek
#   entities:
#     - light.szelfogo
#     - light.etkezo
#     - light.kozlekedo
#    - light.konyha

# - platform: group
#   name: Halo
#   entities:
#     - light.spot_1
#     - light.spot_2
#     - light.spot_3

- platform: group
  name: offgroup
  entities:
    - light.szoba
    - light.eloterek